6bM5SzQFpZQ:
  id: 6bM5SzQFpZQ
  title: めざせポケモンマスター(Cover）
  original_title: めざせポケモンマスター
  original_artist: 松本梨香 
G4FUjD_N8YU:
  id: G4FUjD_N8YU
  title: カントリー・ロード（Cover）
  original_title: カントリー・ロード
  original_artist: 本名陽子 
pZN0nHB0qRQ:  
  id: pZN0nHB0qRQ
  title: You Raise Me Up（Cover）
  original_title: You Raise Me Up
  original_artist: Secret Garden
M_ktlIXJhfc:
  id: M_ktlIXJhfc
  title: 学園天国 フィンガー５ （Cover）
  original_title: 学園天国
  original_artist: フィンガー５
oSL2nCSD17g:
  id: oSL2nCSD17g
  title: Sing／Original
  original_title: Sing
  original_artist: Play You. House
6e3KeO4ICKI:
  id: 6e3KeO4ICKI
  title: Sing／Original
  original_title: Sing
  original_artist: Play You. House
6p-B0AgbXtA:
  id: 6p-B0AgbXtA
  title: 【先行配信】竹渕 慶ソロアルバム 『KEI's 8』より「ありがとう」2/26配信スタート
  original_title: 【先行配信】竹渕 慶ソロアルバム 『KEI's 8』より「ありがとう」2/26配信スタート
  original_artist: 竹渕 慶
m354q21Bxh4:
  id: m354q21Bxh4
  title: 【new album】 KEI's 8／竹渕 慶  MV&メッセージ
  original_title: 【new album】 KEI's 8／竹渕 慶  MV&メッセージ
  original_artist: 竹渕 慶
OkPoqIcWxEI:
  id: OkPoqIcWxEI
  title: 今夜はブギーバック／スチャダラパー feat 小沢健二（Cover） LIVE
  original_title: 今夜はブギーバック
  original_artist: スチャダラパー feat 小沢健二
_FkPM-_RrCI:
  id: _FkPM-_RrCI
  title: 潮騒のメモリー／天野春子（小泉今日子）Cover
  original_title: 潮騒のメモリー
  original_artist: 天野春子（小泉今日子）
jYIDnOifvfA:
  id: jYIDnOifvfA
  title: 花の名／Bump Of Chicken（Cover）
  original_title: 花の名
  original_artist: BUMP OF CHICKEN
M8nu4gkOlbI:
  id: M8nu4gkOlbI
  title: 恋におちたら／Crystal kay（Cover）
  original_title: 恋におちたら
  original_artist: Crystal Kay
CZrChkoycBA:
  id: CZrChkoycBA
  title: Follow me／E-Girls （Cover）
  original_title: Follow me
  original_artist: E-girls
lzk4efmFQW4:
  id: lzk4efmFQW4
  title: Sign／Mr Children（Cover）
  original_title: Sign
  original_artist: Mr.Children
gS1QhVpSEds:
  id: gS1QhVpSEds
  title: 12/9リリース！Goose house New Single『LOVE & LIFE』30
  original_title: 12/9リリース！Goose house New Single『LOVE & LIFE』30
  original_artist: Goosehouse
ALdAGOTBLOs:
  id: ALdAGOTBLOs
  title: Goose house 齊藤ジョニー ニューアルバム『She is』12/2リリース
  original_title: Goose house 齊藤ジョニー ニューアルバム『She is』12/2リリース
  original_artist: Goosehouse
se36IdE1_Nw:
  id: se36IdE1_Nw
  title: にんげんっていいな（Cover）
  original_title: にんげんっていいな
  original_artist: にんげんっていいな
hMYpSLRbXMs:
  id: hMYpSLRbXMs
  title: こんどのHOUSEは、ストリーミングでは観られない
  original_title: こんどのHOUSEは、ストリーミングでは観られない
  original_artist: Play You. House
WqlL3YC_Bgg:
  id: WqlL3YC_Bgg
  title: Winter wonderland
  original_title: Winter wonderland
  original_artist: Winter wonderland
zCtE0PgptNs:
  id: zCtE0PgptNs
  title: Sing
  original_title: Sing
  original_artist: Play You. House
MXgTZqGHDhw:
  id: MXgTZqGHDhw
  title: コモリウタ(Original）／閃光花火＋PYHouse
  original_artist: 閃光花火＋PYHouse
  original_title: コモリウタ
JhjQps5WcUc:
  id: JhjQps5WcUc
  title: ハイウェイ賛歌（Original）／齋藤ジョニー＆関取花
  original_artist: 齋藤ジョニー＆関取花
  original_title: ハイウェイ賛歌
14Zl8mWKUzk:
  id: 14Zl8mWKUzk
  title: 汽車のうた（Original）／関取花＆齋藤ジョニー
  original_artist: 関取花＆齋藤ジョニー
  original_title: 汽車のうた
Ks9G4_vTFN4:
  id: Ks9G4_vTFN4
  title: 11/13リリース！Goose house Phrase#02 Sky
  original_artist: Goosehouse
  original_title: 11/13リリース！Goose house Phrase#02 Sky
Galpr9dwJuk:
  id: Galpr9dwJuk
  title: ３/４／Goose house（Original）
  original_artist: Goosehouse
  original_title: ３/４
kuQO-48SXOg:
  id: kuQO-48SXOg
  title: I Saw Mommy Kissing Santa Claus／Goose house（Cover）
  original_artist: Goosehouse
  original_title: I Saw Mommy Kissing Santa Claus
ktfSsX43BFg:
  id: ktfSsX43BFg
  title: 12/2リリース 齊藤ジョニー『She is』 trial listening
  original_artist: 齊藤ジョニー
  original_title: 12/2リリース 齊藤ジョニー『She is』 trial listening
ALdAGOTBLOs:
  id: ALdAGOTBLOs
  title: Goose house 齊藤ジョニー ニューアルバム『She is』12/2リリース
  original_artist: 齊藤ジョニー
  original_title: Goose house 齊藤ジョニー ニューアルバム『She is』12/2リリース
